import type { Listing } from '../types/listing';

// Mock data to build the Recipient UI against until the backend GET /listings is live.
// Shapes match PRD §10.2 exactly.

const inHours = (h: number) => new Date(Date.now() + h * 3600 * 1000).toISOString();

export const mockListings: Listing[] = [
  {
    _id: 'mock-1',
    donorName: 'Perera Bakery',
    donorType: 'bakery',
    foodItem: 'Bread loaves',
    quantity: 20,
    quantityUnit: 'loaves',
    forWhom: 'both',
    location: 'Ratnapura Town',
    pickupWindowStart: inHours(1),
    pickupWindowEnd: inHours(4),
    contactNumber: '0771234567',
    notes: 'Freshly baked this morning, still soft.',
    status: 'available',
  },
  {
    _id: 'mock-2',
    donorName: 'Green Leaf Hotel',
    donorType: 'hotel',
    foodItem: 'Rice & curry packets',
    quantity: 15,
    quantityUnit: 'packets',
    forWhom: 'people',
    location: 'Colombo 6',
    pickupWindowStart: inHours(0.5),
    pickupWindowEnd: inHours(2),
    contactNumber: '0759876543',
    status: 'available',
  },
  {
    _id: 'mock-3',
    donorName: 'Sunrise Restaurant',
    donorType: 'restaurant',
    foodItem: 'Cooked vegetables',
    quantity: 8,
    quantityUnit: 'kg',
    forWhom: 'animals',
    location: 'Kandy',
    pickupWindowStart: inHours(1),
    pickupWindowEnd: inHours(3),
    contactNumber: '0812223344',
    notes: 'Best for animal shelters.',
    status: 'available',
  },
  {
    _id: 'mock-4',
    donorName: 'Mount Bakers',
    donorType: 'bakery',
    foodItem: 'Cakes & pastries',
    quantity: 30,
    quantityUnit: 'items',
    forWhom: 'people',
    location: 'Nugegoda',
    pickupWindowStart: inHours(2),
    pickupWindowEnd: inHours(5),
    contactNumber: '0763334455',
    status: 'available',
  },
  {
    _id: 'mock-5',
    donorName: 'Ocean View Hotel',
    donorType: 'hotel',
    foodItem: 'Buffet leftovers',
    quantity: 10,
    quantityUnit: 'kg',
    forWhom: 'both',
    location: 'Galle',
    pickupWindowStart: inHours(0.5),
    pickupWindowEnd: inHours(2.5),
    contactNumber: '0912556677',
    status: 'claimed',
    claimedBy: 'Robin Hood Army SL - Galle Chapter',
    claimedAt: inHours(-0.5),
  },
  {
    _id: 'mock-6',
    donorName: 'Spice Garden',
    donorType: 'restaurant',
    foodItem: 'Fried rice',
    quantity: 12,
    quantityUnit: 'plates',
    forWhom: 'people',
    location: 'Negombo',
    pickupWindowStart: inHours(1),
    pickupWindowEnd: inHours(3),
    contactNumber: '0784445566',
    status: 'available',
  },
];
